stages:
  importation:
    cmd: python src/data/import_raw_data.py
    deps:
    - src/data/import_raw_data.py
    outs:
    - data/raw
  split_and_normalize:
    cmd: bash src/data/start.sh
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/processed
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed
    - src/models/train_model.py
    outs:
    - models/rf_model.pkl
  pred_and_eval:
    cmd: python src/models/predict.py
    deps:
    - models/rf_model.pkl
    - src/models/predict.py
    outs:
    - data/pred/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
